server:
  host: 0.0.0.0
  port: 8080
  debug: true
printer:
  auto_detect: true
  port: /dev/ttyUSB0
  baudrate: 115200
  firmware_type: auto
  temp_poll_interval: 30.0
  position_poll_interval: 30.0
  timeout: 5
logging:
  level: DEBUG
  file: logs/factor-client.log
  max_size: 10MB
  backup_count: 5
system:
  hostname: factor-client
  timezone: UTC
  power_management:
    enable_watchdog: true
    auto_reboot_on_error: true
    max_error_count: 5
  network:
    wifi_country: US
    enable_ssh: true
    enable_vnc: false
  storage:
    enable_readonly_root: true
    log_to_ram: true
display:
  enable: false
  type: ssd1306
  width: 128
  height: 64
notifications:
  enable: false
  methods: []
camera:
  enable: false
  stream_url: ''
  snapshot_url: ''
printer:
  auto_detect: true
  port: /dev/ttyUSB0
  baudrate: 115200
  firmware_type: auto
  temp_poll_interval: 30.0
  position_poll_interval: 30.0
  timeout: 5
  firmware_support:
    - marlin
    - repetier
    - smoothieware
    - grbl
